version: '3.8'

services:
  postgres_db:
    image: postgres:15-alpine
    container_name: equipex_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 159357
      POSTGRES_DB: equ
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - core_network

  stats_extractor:
    build:
      context: ./SportsPlatform.Auth/SportsPlatform.Auth.Api/scripts
      dockerfile: Dockerfile.stats-extractor
    container_name: equipex_stats_extractor
    command: uvicorn stats_extractor_api:app --host 0.0.0.0 --port 8102
    expose:
      - "8102"
    networks:
      - core_network

  dotnet_backend:
    build:
      context: ./SportsPlatform.Auth
      dockerfile: Dockerfile
    container_name: equipex_dotnet_backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__DefaultConnection=Host=postgres_db;Port=5432;Database=equ;Username=postgres;Password=159357
      - StatsExtractor__BaseUrl=http://stats_extractor:8102
      - Microservice__BaseUrl=http://34.154.162.32:8000
      - Storage__Provider=S3
      - Storage__BucketName=equipex-media-storage
    ports:
      - "5000:5000"
    depends_on:
      - postgres_db
      - stats_extractor
    networks:
      - core_network

volumes:
  postgres_data:

networks:
  core_network:
    driver: bridge
