-- Legacy note:
-- The original RLS policies in this file were based on:
--   - app.user_roles
--   - team.manager_user_id
--   - user_role / team_manager legacy tables
--
-- The active v8 runtime model now uses:
--   - app.user_id
--   - app.is_admin
--   - club / club_membership / team / team_membership / invitation
--
-- See:
--   scripts/migrations/005_role_constraints_and_rls_v8.sql
--   scripts/migrations/006_v8_membership_rls_policies.sql
--
-- Keep this file only as historical reference until the legacy approval/role
-- schema is fully removed.
